allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - workerd
  - unrs-resolver
  - "@prisma/engines"
  - prisma
  - bcrypt
